In [11]:
import numpy as np
import scipy
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
print(x[5])

5


In [33]:
print(x[1:2])

[1]


In [34]:
x = np.array([[ 0,  1,  2],
            [ 3,  4,  5],
            [ 6,  7,  8],
            [ 9, 10, 11]])

In [51]:
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [52]:
type(x)

numpy.ndarray

In [47]:
print(x[:,1:3]) #zeile 1:bis exkl.3,spalte 1: bis exkl. 3

[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]


In [48]:
x = np.array([(0,  1,  2),
            (3,  4,  5),
            (6,  7,  8),
            (9, 10, 11)])

In [49]:
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [55]:
type(x[1])

numpy.ndarray

In [56]:
print(x[1,0])

3
